[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught (in promise) Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 9, columns 16--37) Field \"\u001B[34mdate-format\u001B[39m\" has value \u001B[34m[Semester 1, 2022-23]\u001B[39m, which must instead be a string\n 8: \u001B[34m  date: today\u001B[39m\n 9: \u001B[34m  date-format: [Semester 1, 2022-23]\u001B[39m\n                  ~~~~~~~~~~~~~~~~~~~~~~\n10: \u001B[34m  chapters:\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34m[Semester 1, 2022-23]\u001B[39m is of type an array.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mbook\u001B[39m:\u001B[34mdate-format\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m20063\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m45521\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m45376\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m78999\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
